char        =  { ASCII_ALPHANUMERIC | "." | "/" }
whitespaces = _{ " "+ }
whitespaces_opt = _{ " "* }
STRING = @{ (char|" ")* }
STRING_WRAPPER = _{ "\"" ~ STRING ~ "\"" }
WORD = @{ char+ }
NAME        = @{ char+ }
ARGUMENT    = { whitespaces ~ (STRING_WRAPPER|WORD) }
// Has To be trimmed
CALL        = { NAME ~ ARGUMENT* }
PIPE        = { "|" ~ whitespaces_opt ~ CALL }
REDIRECTION = { ">" ~ whitespaces_opt ~ CALL }
EXPR        = { ((PIPE | REDIRECTION | CALL) ~ whitespaces_opt)+ }